#!/usr/bin/perl
use strict;
# Customize these variables.
my $title = "The Songbee Song Projection System";
my @chapters = qw(
    intro
    playlists
    live
    editing
);

my $dtd = "/sw/share/xml/dtd/docbookx/4.2.0/docbookx.dtd";
my $fo_stylesheet = "/sw/share/xml/xsl/docbook-xsl/fo/docbook.xsl";
my $html_stylesheet = "/sw/share/xml/xsl/docbook-xsl/xhtml/chunk.xsl";
my $fop = "/Users/simon/Desktop/trunk/fop";
my ($first, $last) = qw(Simon Cozens);
# END of customization

my @ents;

my $file = "ch00";
for (@chapters) {
    $_ .= ".xml";
    if (!-e $_) {
        open OUT, ">$_" or die $!;
        print OUT <<EOF ;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chapter PUBLIC "-//OASIS//DTD DocBook XML V4.2//EN"
          "$dtd">
<chapter>
  <title>XXX</title>
  <para>
  </para>
</chapter>
EOF
    }
    push @ents, $file;
    system("tail +4 $_ > ".($file++).".xml");
}

open BOOK, ">book.xml" or die $!;
print BOOK <<EOF;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook XML V4.2//EN"
          "$dtd"
[
EOF

# Now our entities
print BOOK "<!ENTITY $_ SYSTEM \"$_.xml\">\n" for @ents;

print BOOK <<EOF;
]>

<book>
  <title>$title</title>
  <bookinfo>
    <authorgroup>
      <author>
	<firstname>$first</firstname>
	<surname>$last</surname>
      </author>
    </authorgroup>
    <edition>Draft</edition>
    <copyright>
      <!-- obviously this will change in the final version -->
      <year>2006-2007</year>
      <holder>$first $last</holder>
    </copyright>
    <edition>1st</edition>
  </bookinfo>

EOF

print BOOK "&$_;\n" for @ents;
print BOOK "</book>\n";

# Makefile to build the book from the raw XML files
open OUT, ">Makefile" or die $!;
print OUT <<EOF
CHAPTERS = @chapters
PDFCHAPTERS = \$(CHAPTERS:.xml=.pdf)
FO_STYLESHEET = $fo_stylesheet
HTML_STYLESHEET = $html_stylesheet
MANIFEST = Makefile \$(CHAPTERS) bookmaker
FOP = $fop

.SUFFIXES:
.SUFFIXES: .xml .fo .pdf
#
.fo.pdf:
	\$(FOP) \$< \$@

.xml.fo:
	xsltproc \$(FO_STYLESHEET) \$< > \$@

all: book.pdf htmlbook

dist: 
	tar czvf book.tar.gz \$(MANIFEST)

pdfdist: pdfchapters
	tar czvf pdfs.tar.gz \$(PDFCHAPTERS)

htmlbook:
	xsltproc -stringparam base.dir html/ \$(HTML_STYLESHEET) book.xml

pdfchapters: \$(PDFCHAPTERS)

book.xml: \$(CHAPTERS)
	perl bookmaker

book.fo: book.xml
	xsltproc \$(FO_STYLESHEET) book.xml > book.fo

latexpdf: book.fo
	 pdflatex "&pdfxmltex" book.fo ; pdflatex "&pdfxmltex" book.fo

latexdvi: book.fo
	 latex "&xmltex" book.fo ; latex "&xmltex" book.fo
EOF
