#!/usr/bin/perl
use strict;
# Customize these variables.
my $title = "The Songbee Song Projection System";
my @chapters = qw(
    intro
    playlists
    live
    editing
);

my $dtd = "/sw/share/xml/dtd/docbookx/4.2.0/docbookx.dtd";
my $fo_stylesheet = "docbook.xsl";
my $html_stylesheet = "/sw/share/xml/xsl/docbook-xsl/xhtml/chunk.xsl";
my $fop = "/Users/simon/svn/fop/fop -c /Users/simon/svn/fop/fop/conf/fop.xconf";
my ($first, $last) = qw(Simon Cozens);
# END of customization

my @ents;

my $file = "ch00";
for (@chapters) {
    $_ .= ".xml";
    if (!-e $_) {
        open OUT, ">$_" or die $!;
        print OUT <<EOF ;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chapter PUBLIC "-//OASIS//DTD DocBook XML V4.2//EN"
          "$dtd">
<chapter>
  <title>XXX</title>
  <para>
  </para>
</chapter>
EOF
    }
    push @ents, $file;
    system("tail -n +4 $_ > ".($file++).".xml");
}

open BOOK, ">book.xml" or die $!;
print BOOK <<EOF;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book PUBLIC "-//OASIS//DTD DocBook XML V4.2//EN"
          "$dtd"
[
EOF

# Now our entities
print BOOK "<!ENTITY $_ SYSTEM \"$_.xml\">\n" for @ents;

print BOOK <<EOF;
]>

<book>
  <title>$title</title>
  <bookinfo>
    <authorgroup>
      <author>
	<firstname>$first</firstname>
	<surname>$last</surname>
      </author>
    </authorgroup>
    <edition>Draft</edition>
    <copyright>
      <year>2006-2009</year>
      <holder>$first $last</holder>
    </copyright>
    <edition>1st</edition>
  </bookinfo>

EOF

print BOOK "&$_;\n" for @ents;
print BOOK "</book>\n";
